sudo: required
services:
  - docker

before_install
  - docker build -t chaseovidiu/docker-react -f Dockerfile.dev .

script:
   - docker run chaseovidiu/docker-react npm run test -- --coverage
    
    


